### ISSUE TITLE
make Error 

### ISSUE THREAD

**Issue by mmi333** [strukturag/vlc-libde265#9]
Recently, vlc crashed (segmentation fault (core dumped)) with HEVC encoded files. mpv, however, works fine. Since I am running Fedora 27, I couldn't install this plugin via apt-get, and when I attempted to install it from github, after running "./autogen.sh; ./configure", make has an error. 

make  all-am
make[1]: Entering directory '/vlc-libde265'
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DMODULE_STRING=\"de265\"  -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE   -DMODULE_STRING=\"de265\"  -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE  -DVLC_MODULE_COPYRIGHT="\"Copyright \(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c -o src/codec/libde265_plugin_la-libde265dec.lo `test -f 'src/codec/libde265dec.c' || echo './'`src/codec/libde265dec.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DMODULE_STRING=\"de265\" -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -DMODULE_STRING=\"de265\" -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE "-DVLC_MODULE_COPYRIGHT=\"Copyright \\(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c src/codec/libde265dec.c  -fPIC -DPIC -o src/codec/.libs/libde265_plugin_la-libde265dec.o
src/codec/libde265dec.c: In function ‘Decode’:
src/codec/libde265dec.c:369:13: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_pace_control’
     if (!dec->b_pace_control && (sys->late_frames > 0) &&
             ^~
src/codec/libde265dec.c:377:13: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_pace_control’
     if (!dec->b_pace_control &&
             ^~
src/codec/libde265dec.c: In function ‘Open’:
src/codec/libde265dec.c:864:10: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘pf_decode_video’; did you mean ‘pf_queue_video’?
     dec->pf_decode_video = Decode;
          ^~~~~~~~~~~~~~~
          pf_queue_video
src/codec/libde265dec.c:871:10: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_need_packetized’; did you mean ‘pf_packetize’?
     dec->b_need_packetized = true;
          ^~~~~~~~~~~~~~~~~
          pf_packetize
make[1]: *** [Makefile:827: src/codec/libde265_plugin_la-libde265dec.lo] Error 1
make[1]: Leaving directory '/vlc-libde265'
make: *** [Makefile:566: all] Error 2

**Comment by hnguyen48206** [comment]
Did you find any solution to this matter Sir? @mmi333 cause it seems like I'm having the same one with the lastest release, I need to build the plugin for vlc 3.x on Linux. Thank Sir.

**Comment by mmi333** [comment]
I don't remember having solved this, I moved to mpv since. But if I recall correctly it was mostly a dependency problem for me.

Good Luck.
